sudo: required

install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - pwd
  - ls -lah

before_script:
  - cd ../
  - wget https://github.com/ArroyoLabs/erdiko-core/archive/develop.zip
  - unzip develop.zip
  - mv erdiko-core-develop erdiko-core
  - ls -lah
  # - cd ../ && sudo git clone -b develop https://github.com/ArroyoLabs/erdiko-core.git
  # - cd git sudo clone -b develop https://github.com/ArroyoLabs/erdiko-wordpress.git
  - cd erdiko-dev

script:
  - ls -lah
  - sudo docker-compose up -d
  - sudo docker-compose ps
  - sudo chmod 770 unittests.sh
  - sudo docker exec erdiko_php /code/unittests.sh

notifications:
  email:
    - john@arroyolabs.com 
