sudo: required

install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose

script:
  - ls -lah
  - sudo docker-compose up -d
  - sudo docker-compose ps
  - sudo docker exec erdiko_php7 ls -lah

notifications:
  email:
    - john@arroyolabs.com 
