sudo: required

install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - pwd
  - ls -lah
  - cd ../ && sudo git clone -b develop https://github.com/ArroyoLabs/erdiko-core.git
  - cd git sudo clone -b develop https://github.com/ArroyoLabs/erdiko-wordpress.git
  - cd erdiko-dev

script:
  - ls -lah
  - sudo docker-compose up
  - sudo docker-compose ps
  - sudo docker exec erdiko_php7 cd /erdiko-core/tests && phpunit AllTests

notifications:
  email:
    - john@arroyolabs.com 
