version: '2'

services:
  data:
    image: busybox
    volumes:
      - .:/code
      - ../erdiko-core:/erdiko-core
      - ../erdiko-wordpress:/erdiko-wordpress  
  webserver:
    container_name: erdiko_nginx
    image: nginx:latest
    env_file: environment.env
    volumes_from: [data]
    volumes:
      - ./docker/nginx/site-multisite.conf:/etc/nginx/conf.d/site.conf
      - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    ports:
      - "8088:80"
  php:
    container_name: erdiko_php7
    env_file: environment.env
    image: erdiko_php7fpm
    build:
      context: ./docker/php7
      dockerfile: Dockerfile-utest
    volumes_from: [data]
    volumes:
      - ./docker/php7/conf.d:/usr/local/etc/php/conf.d